DROP DATABASE IF EXISTS DBCASSINO;

CREATE DATABASE DBCASSINO;

USE DBCASSINO;

CREATE TABLE PLAYER (
	IDPLAYER INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAMEPLAYER VARCHAR(100),
    BALANCE DECIMAL(8,2) NOT NULL
);

CREATE TABLE BET (
	IDTRANSACTION INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDPLAYER INT NOT NULL,
	BETVALUE DECIMAL(8,2) NOT NULL	
);

CREATE TABLE WIN (
	IDTRANSACTION INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDPLAYER INT NOT NULL,
	TRANSACTIONVALUE DECIMAL(8,2) NOT NULL	
);